# Generated by Django 4.0.6 on 2022-08-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=20, null=True, verbose_name='앱이름')),
                ('review_id', models.TextField(blank=True, null=True, verbose_name='리뷰ID')),
                ('user_name', models.TextField(blank=True, null=True, verbose_name='사용자')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='별점')),
                ('source', models.CharField(blank=True, max_length=10, null=True, verbose_name='구분')),
                ('at', models.DateTimeField(blank=True, null=True, verbose_name='작성일')),
                ('reply_content', models.TextField(blank=True, null=True, verbose_name='답변')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'db_table': 'review',
                'ordering': ['-at'],
                'managed': True,
            },
        ),
    ]
