# Generated by Django 4.0.6 on 2022-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_review_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='별점'),
        ),
    ]
